server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /Consulta%20(15).csv {
    default_type text/csv;
    try_files "/Consulta (15).csv" =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
